#!/usr/bin/env python3

import sys

from core.TetrisEngine import TetrisEngine
from collections import deque

def main():
    tetris_engine = TetrisEngine()
    for line in sys.stdin:
        # If line is not commented
        if line[0] != '#':
            result = tetris_engine.process_line(line.strip())
            sys.stdout.write(str(result) + "\n")


if __name__ == "__main__":
    main()
